server:
  port: 9001

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  cache:
    type: redis
    redis:
      time-to-live: 3600000

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30  # Default is 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # Increase from 10 to 30
    lease-expiration-duration-in-seconds: 90  # Increase accordingly

jwt:
  secret: asdfladf98255f89aysf255yasiudfha9s87df255syudhfa98sdfyaisuhdfa98sfy
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.social.user: DEBUG
#    com.social.user: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.springframework.cloud.netflix.eureka: WARN
    com.netflix.discovery: WARN
    org.springframework.web.client.RestTemplate: WARN
#    org.springframework.cloud.netflix.eureka: ERROR
#    com.netflix.discovery: ERROR
#    org.springframework.web.client.RestTemplate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service/user-service.log


