# Docker Profile - Uses Docker container hostnames
# Run with: SPRING_PROFILES_ACTIVE=docker

spring:
  datasource:
    url: jdbc:postgresql://postgres-orders:5434/commerce_orders_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://commerce-service-discovery:8761/eureka/

logging:
  level:
    com.social.order: INFO