# Configuration for commerce-users-service
server:
  port: ${SERVER_PORT:9001}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/commerce_users_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

jwt:
  secret: ${JWT_SECRET:asdfladf98255f89aysf255yasiudfha9s87df255syudhfa98sdfyaisuhdfa98sfy}
  expiration: ${JWT_EXPIRATION:86400000}

