server:
  port: 9006

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db
      database: notification_db

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: notification-service

