server:
  port: 9004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

