server:
  port: 9005

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/social_db?useSSL=false
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

